# Site settings
title: UX with Paul
email: paul@paulklipp.com
description: > # this means to ignore newlines until "baseurl:"
  I'm teaching myself LeanUX, Design Thinking, design ethnography, and frontend coding and sharing the journey here
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://uxwithpaul.com" # the base hostname & protocol for your site
twitter_username: paulklipp
github_username:  pklipp
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Build settings
markdown: kramdown